package CheckForm;

import javax.swing.*;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddID_Auto {

    private Map<String, JTextField> textFieldMap = new HashMap<>();
    private Timer timer;

    public void initTextFieldMap(Object formObject) {
        Field[] fields = formObject.getClass().getDeclaredFields();
        for (Field field : fields) {
            if (field.getType() == JTextField.class) {
                try {
                    field.setAccessible(true);
                    JTextField textField = (JTextField) field.get(formObject);
                    textFieldMap.put(field.getName(), textField);
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            }
        }
        startAutoUpdate();
    }

    private void startAutoUpdate() {
        // Khởi tạo Timer với khoảng thời gian 3 giây (3000 milliseconds)
        timer = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setTextFieldValues();
            }
        });
        timer.start();
    }

    public void stopAutoUpdate() {
        if (timer != null) {
            timer.stop();
        }
    }

    public void setTextFieldValues() {
        textFieldMap.forEach((name, textField) -> {
            // Kiểm tra nếu ô nhập liệu chứa "ID" và ô nhập liệu hiện tại rỗng
            if (name.contains("ID") && textField.getText().trim().isEmpty()) {
                String autoGeneratedId = generateAutoId(name);
                textField.setText(autoGeneratedId);
                textField.setEnabled(false); // Không cho phép người dùng chỉnh sửa mã tự động
            }
        });
    }

    private String generateAutoId(String fieldName) {
        String autoId = "";
        String[] parts = fieldName.split("ID");
        if (parts.length > 1) {
            String suffix = parts[1];
            for (char c : suffix.toCharArray()) {
                if (Character.isUpperCase(c)) {
                    autoId += c;
                }
            }
        }
        autoId += generateRandomNumber();
        return autoId;
    }

    private String generateRandomNumber() {
        Random random = new Random();
        int randomNumber = random.nextInt(9000) + 1000;
        return String.valueOf(randomNumber);
    }
}
