package CheckForm;

import javax.swing.*;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class AddID_Auto {

    private Map<String, JTextField> textFieldMap = new HashMap<>();

    public void initTextFieldMap(Object formObject) {
        Field[] fields = formObject.getClass().getDeclaredFields();
        for (Field field : fields) {
            if (field.getType() == JTextField.class) {
                try {
                    field.setAccessible(true);
                    JTextField textField = (JTextField) field.get(formObject);
                    textFieldMap.put(field.getName(), textField);
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public void setTextFieldValues() {
        textFieldMap.forEach((name, textField) -> {
            //textField.setText(name);
          
            //textField.setBorder((Border) red);
            if (name.contains("ID")) {
                String autoGeneratedId = generateAutoId(name);
                textField.setText(autoGeneratedId);  
                textField.setEnabled(false);
            //textField.setBackground(Color.gray);
            }
        });
    }

    private String generateAutoId(String fieldName) {
        String autoId = "";
        String[] parts = fieldName.split("ID");
        if (parts.length > 1) {
            String suffix = parts[1];
            for (char c : suffix.toCharArray()) {
                if (Character.isUpperCase(c)) {
                    autoId += c;
                }
            }
        }
        autoId += generateRandomNumber();
        return autoId;
    }

    private String generateRandomNumber() {
        Random random = new Random();
        int randomNumber = random.nextInt(9000) + 1000;
        return String.valueOf(randomNumber);
    }
}
