package CheckForm;

import javax.swing.*;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddMK_Auto {

    private Map<String, JTextField> textFieldMap = new HashMap<>();
    private Timer timer;

    public void initTextFieldMap(Object formObject) {
        Field[] fields = formObject.getClass().getDeclaredFields();
        for (Field field : fields) {
            if (field.getType() == JTextField.class) {
                try {
                    field.setAccessible(true);
                    JTextField textField = (JTextField) field.get(formObject);
                    textFieldMap.put(field.getName(), textField);
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            }
        }
        startAutoUpdate();
    }

    private void startAutoUpdate() {
        // Khởi tạo Timer với khoảng thời gian 3 giây (3000 milliseconds)
        timer = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setTextFieldValues();
            }
        });
        timer.start();
    }

    public void stopAutoUpdate() {
        if (timer != null) {
            timer.stop();
        }
    }

    public void setTextFieldValues() {
        textFieldMap.forEach((name, textField) -> {
            // Kiểm tra nếu ô nhập liệu chứa "MK" và ô nhập liệu hiện tại rỗng
            if (name.contains("MK") && textField.getText().trim().isEmpty()) {
                String autoGeneratedPassword = generateAutoPassword();
                textField.setText(autoGeneratedPassword);
                textField.setEnabled(false); // Không cho phép người dùng chỉnh sửa mật khẩu tự động
            }
        });
    }

    public String generateAutoPassword() {
        String upperCaseLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String specialCharacters = "@#$%^&_";
        String digits = "0123456789";
        String allCharacters = upperCaseLetters + specialCharacters + digits;

        StringBuilder password = new StringBuilder();
        Random random = new Random();

        // Ensure at least one uppercase letter, one special character, and one digit
        password.append(upperCaseLetters.charAt(random.nextInt(upperCaseLetters.length())));
        password.append(specialCharacters.charAt(random.nextInt(specialCharacters.length())));
        password.append(digits.charAt(random.nextInt(digits.length())));

        // Fill the rest of the password to ensure length > 6
        int remainingLength = random.nextInt(3) + 4; // Ensures length is at least 7
        for (int i = 0; i < remainingLength; i++) {
            password.append(allCharacters.charAt(random.nextInt(allCharacters.length())));
        }

        return password.toString();
    }
}
