/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DuAn.com.UI;



import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author NITRO 5
 */
public class LoadingFrame extends javax.swing.JFrame {
    Timer thoiGian;
    ImageIcon icon;
    /**
     * Creates new form Loading
     */
    public LoadingFrame() {
        initComponents();
        setLocationRelativeTo(null);
        TuChay();
        doiIcon();
    }
     public void TuChay()
    {
         thoiGian = new Timer(20, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
               int giaTriHienTai = prbLoad.getValue();
               giaTriHienTai = giaTriHienTai + 1;
               prbLoad.setValue(giaTriHienTai);
               
               if (giaTriHienTai > 100)
               {
                   thoiGian.stop();
                   dispose();//tắt form load tự tắt
                   new LoginFrame().setVisible(true); //mở form ví dụ 1 lên
                   //JOptionPane.showMessageDialog(rootPane, "Download hoàn thành");
               }
            }
        });
        thoiGian.start();
    }
     public void doiIcon() {
        icon = new ImageIcon("src/main/resources/images/software_256.png");
        setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        prbLoad = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backRound1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        prbLoad.setBackground(new java.awt.Color(204, 204, 204));
        prbLoad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prbLoad.setForeground(new java.awt.Color(102, 153, 255));
        prbLoad.setMaximum(200);
        prbLoad.setString("\n");
        prbLoad.setStringPainted(true);
        getContentPane().add(prbLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 600, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //FlatIntelliJLaf.setup();
        /* Create and display the form */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //FlatIntelliJLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar prbLoad;
    // End of variables declaration//GEN-END:variables
}
